import string
import threading
from time import sleep, time

name = input("Alright, welcome to the program, let's start with an easy question; What is your name? ")
hometown = input("Great! Next question, Where are you from? ")

print("Alright, Hello, " + name, "! From " + hometown, ".")
sleep(1)
print("Saving Info")
sleep(1)
print("Saving Info.")
sleep(1)
print("Saving Info..")
sleep(1)
print("Saving Info...")
sleep(1)
print("Success!")
sleep(5)
print(" _____    _______   _____   __  __")
sleep(0.5)
print("|  __ \  |__   __| |_   _| |  \/  |")
sleep(0.5)
print(" | |__) |    | |      | |   | \  / |")
sleep(0.5)
print(" |  _  /     | |      | |   | |\/| ")
sleep(0.5)
print("| | \ \     | |     _| |_  | |  | |")
sleep(0.5)
print("|_|  \_\    |_|    |_____| |_|  |_|")
sleep(0.5)
print("'Random Thing I Made (RTIM)'")
sleep(5)
print("Thank you for coming" + name, "My name is 'Random Thing I Made'. Or for short, 'RTIM'")
sleep(3)
print("What would you like to do " + name, "?")
sleep(1)
answer = input("(C)alculator, well just calculator i havent figured anything else out yet :( ")
if answer == "C":
    choose = input("Which one would you like, Plus(+), Minus(-), Multiplication(*), Division(/) ")
if choose == "+":
     One = input("First: ")
     Two = input("Second: ")
     sum = int(One) + int(Two)
     print(str(sum))
     sleep(3)
     print("cool! now restart because its gonna take my creator a really long time to code to make you go to the menu")
     sleep(10)
     print("NOW QUIT")
if choose == "-":
     One = input("First: ")
     Two = input("Second: ")
     sum = int(One) - int(Two)
     print(str(sum))
     sleep(3)
     print("cool! now restart because its gonna take my creator a really long time to code to make you go to the menu")
     sleep(10)
     print("NOW QUIT")
if choose == "*":
     One = input("First: ")
     Two = input("Second: ")
     sum = int(One) * int(Two)
     print(str(sum))
     sleep(3)
     print("cool! now restart because its gonna take my creator a really long time to code to make you go to the menu")
     sleep(10)
     print("NOW QUIT")
if choose == "/":
        One = input("First: ")
        Two = input("Second: ")
        sum = int(One) / int(Two)
        print(str(sum))
        sleep(3)
        print("cool! now restart because its gonna take my creator a really long time to code to make you go to the menu")
        sleep(10)
        print("NOW QUIT")
